development:
  GOOGLE_API_KEY: "AIzaSyB01fu7jjQeTWnmeP_5cacIWXV_U5XHg4U"
  CLOUDINARY_URL: "cloudinary://845967915794319:K7kJkXGnETBq5aSzxBmBXsMWnSA@aafke"

production:
  HOST: 'sneakertours.herokuapp.com'
  POSTMARK_API_TOKEN: "7ad6e632-40c4-4359-88b1-7f9c0ec3e5c6"

