meta_title: "Sneaker Tours"
meta_description: "Your alternative guide through Amsterdam"
meta_image: "http://res.cloudinary.com/aafke/image/upload/v1470926452/fb-thumbnail_ltidmu.jpg"  # A picture in your app / assets / images /
twitter_account: "@SneakerTours"  # essential for Twitter Cards
