meta_title: "Sneaker Tours"
meta_description: "Your alternative guide through Amsterdam"
meta_image: "st-folded.jpg"  # A picture in your app / assets / images /
# twitter_account: "@nomdevotrecompte"  # essential for Twitter Cards
