meta_title: "Sneaker Tours"
meta_description: "Your alternative guide through Amsterdam"
meta_image: "st-picture.jpg"  # A picture in your app / assets / images /
twitter_account: "@SneakerTours"  # essential for Twitter Cards
